config/routes.rb
# Rails router
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/home'

  resources :students do
    collection do
      get 'own_index'
    end
  end
  devise_for :teachers

  resources :courses do
    collection do
      get 'own_index'
    end
    member do
      get :all_qr
      post :export
    end
    resources :students
    resources :assistances, only: [:index]
  end

  resources :teachers do
    collection {post :import}
  end

  resources :students do
    collection { post :import }
    member do
      get :generate_qr
    end
  end

  resources :teachers do
    resources :courses do
      resources :students
    end
  end

  resources :assistances, only: [:index] do
    member do
      put :change_assist
    end
  end

  get 'welcome/index'

  get 'admin/display'
  get 'admin/add_teacher'
  get 'admin/add_student'
  get 'admin/add_student2'
  post 'admin/add_student3'
  get 'admin/student_courses_index'

  get 'welcome/metrics', to: 'welcome#metrics', as: 'welcome_metrics'
  get 'welcome/data', to: 'welcome#data', as: 'welcome_data'
  get 'welcome/student', to: 'welcome#student', as: 'welcome_student'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'Teacher', at: 'auth'
      get 'course_students' => 'content#course_students'
      post 'record_assistance' => 'content#record_assistance'
      delete 'assistance' => 'content#destroy_assistance'
      delete 'all_assistance' => 'content#destroy_all_assistance'
      scope 'course_assistance' do
        get '/:id/:date' => 'content#daily_course_assistance'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
# student model
require 'rqrcode'
require 'csv'
require 'open-uri'
class Student < ApplicationRecord
  has_many :assistances
  has_and_belongs_to_many :courses
  validates :rut, uniqueness: true

  def self.import(file)
    begin
      CSV.foreach(file.path, headers:true) do |row|
        Student.create! row.to_hash
      end
    rescue => error
      return error
    end
  end

  def self.export(options = {})
    attributes = %w{name last_name rut}
    @csv = CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |student|
        csv << student.attributes.values_at(*attributes)
      end
    end
    puts "CSV: "+ @csv
    return @csv
  end

  def gen_qr
    qrcode = RQRCode::QRCode.new(rut)
# With default options specified explicitly
    tmp_path = Rails.root.join('tmp', rut)
    png = qrcode.as_png(
        resize_gte_to: false,
        resize_exactly_to: false,
        fill: 'white',
        color: 'black',
        size: 120,
        border_modules: 4,
        module_px_size: 6,
        file: tmp_path # path to write
    )
    [png, tmp_path]
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :generate_qr]
  before_action :authenticate_teacher!
  before_action :authenticate_admin!, except: [:own_index, :show]


  def generate_qr
    tuple = @student.gen_qr
    send_data tuple[0], type: 'image/png', filename: @student.rut
    File.delete(tuple[1])
    #render json: nil, status: :ok
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html
      format.csv { send_data @students.export }
    end
  end

  def own_index
    aux = Student.all
    @students = []
    aux.each do |student|
      student.courses.each do |course|
        @students << student if course.teacher == current_teacher
      end
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @import = ""
    begin
      @import = Student.import(params[:file])

      if @import == true
        redirect_to students_url notice: "Activity Data Imported"
      else
        redirect_to students_url notice: @import.to_s
      end
    rescue => error
      flash.now[:alert] = error
      redirect_to student_url notice: error.to_s
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :last_name, :rut)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :student_last_name, class: 'form-control' %>
  </div>

    <div class="field">
      <%= form.label :rut %>
      <%= form.text_field :rut, id: :rut, class: 'form-control' %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="col-md-2">

</div>
<div class="col-md-2">

</div>
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-body">
      <h1>Students</h1>
      <%= link_to 'New Student', new_student_path %>
      <table class="table table-hover">
        <thead>
        <tr>
          <th width='15%'>Name</th>
          <th width='15%'>Last name</th>
          <th width='30%'>RUT</th>
          <th colspan="3"></th>
          <th width='30%'></th>
        </tr>
        </thead>

        <tbody>
        <% @students.each do |student| %>
            <tr>
              <td><%= student.name %></td>
              <td><%= student.last_name %></td>
              <td><%= student.rut %></td>
              <td><%= link_to 'Show', student %></td>
              <td><%= link_to 'Edit', edit_student_path(student) %></td>
              <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td ><%= link_to 'Generate QR', generate_qr_student_path(student.id), class:'blue_btn' %><td >

            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div>
      <h1>Import Students</h1>
      <%= form_tag import_students_path, multipart:true do %>
        <%=file_field_tag :file%>
        <%=submit_tag "Import CSV",class:'btn-success'%>
      <% end %>
    </div>
    <div>
      <h1>Export teachers csv file</h1>
      <%= button_to "Export Students CSV", "students.csv", method: :get, class:'btn-success' %>
    </div>
  </div>
</div>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/own_index.html.erb
<h1>My Students</h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Last Name</th>
    <th>Student RUT </th>
    <th>Assistance</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.rut %></td>
        <td ><%= link_to 'See Assistance', student, class:'blue_btn' %></td>
        <td ><%= link_to 'Generate QR', generate_qr_student_path(student.id), class:'blue_btn' %><td >
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/students/show.html.erb
<div class="card center">
  <div class="card-header" data-background-color="blue">
    <h2 class="title">
      <% if (@student.last_name!=nil)%>
        <%= @student.name + " "+@student.last_name %>
      <% else %>
        <%= @student.name %>
      <% end %></h2>
  </div>
  <div class="card-content"
      <h1><strong>Assitence:</strong></h1>
      <% @student.courses.each do |course| %>
        <h2><strong>Course: <%= course.subject+" "+course.grade+"-"+course.level%></strong></h2>
        <table class="basic_table">
          <thead>
            <tr>
              <% @student.assistances.each do |ass| %>
                <%if (ass.course_id==course.id)%>
                  <td><%= ass.date.strftime('%m-%d') %></td>
                <% end %>
              <%end%>
            </tr>
          </thead>

          <tbody>
              <tr>
                <% @student.assistances.each do |ass| %>
                  <%if (ass.course_id==course.id)%>
                    <% if (ass.attend )%>
                      <td bgcolor="#88ff88">yes</td>
                    <% else %>
                      <td bgcolor="#ff8888">no</td>
                    <% end %>
                  <% end %>
                <%end%>
              </tr>
          </tbody>
        </table>
      <%end%>

     <br/>

    <!--<%= link_to 'Edit', edit_student_path(@student),class:'blue_btn' %> |-->
    <%= link_to 'Back', admin_student_courses_index_path,class:'blue_btn' %>
  </div>
</div>