config/routes.rb
# Rails router
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/home'

  resources :students do
    collection do
      get 'own_index'
    end
  end
  devise_for :teachers

  resources :courses do
    collection do
      get 'own_index'
    end
    member do
      get :all_qr
      post :export
    end
    resources :students
    resources :assistances, only: [:index]
  end

  resources :teachers do
    collection {post :import}
  end

  resources :students do
    collection { post :import }
    member do
      get :generate_qr
    end
  end

  resources :teachers do
    resources :courses do
      resources :students
    end
  end

  resources :assistances, only: [:index] do
    member do
      put :change_assist
    end
  end

  get 'welcome/index'

  get 'admin/display'
  get 'admin/add_teacher'
  get 'admin/add_student'
  get 'admin/add_student2'
  post 'admin/add_student3'
  get 'admin/student_courses_index'

  get 'welcome/metrics', to: 'welcome#metrics', as: 'welcome_metrics'
  get 'welcome/data', to: 'welcome#data', as: 'welcome_data'
  get 'welcome/student', to: 'welcome#student', as: 'welcome_student'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'Teacher', at: 'auth'
      get 'course_students' => 'content#course_students'
      post 'record_assistance' => 'content#record_assistance'
      delete 'assistance' => 'content#destroy_assistance'
      delete 'all_assistance' => 'content#destroy_all_assistance'
      scope 'course_assistance' do
        get '/:id/:date' => 'content#daily_course_assistance'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/add_student.html.erb
<h1>Course</h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Teacher</th>
    <th>Subject</th>
    <th>Grade</th>
    <th>Level</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
      <tr>
        <td><%= course.teacher.name %></td>
        <td><%= course.subject %></td>
        <td><%= course.grade %></td>
        <td><%= course.level %></td>
        <td><%= link_to 'Add student', admin_add_student2_path(course: course.id), class:'blue_btn' %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Course', new_course_path, class:'blue_btn' %>

app/views/admin/add_student2.html.erb
<h1>Course</h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Teacher</th>
    <th>Subject</th>
    <th>Grade</th>
    <th>Level</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @course.teacher.name %></td>
        <td><%= @course.subject %></td>
        <td><%= @course.grade %></td>
        <td><%= @course.level %></td>
      </tr>
  </tbody>
</table>



<%= form_tag({controller: "admin", action: "add_student3"}, method: "post") do %>
    <div id="InfoTopics">
      <h3 class="uppercase mb8">Possible Students to Add</b> <i id="tooltip" class="fa fa-question-circle" title="Selecciona todos los themes que desees agregar a la infografia."></i>&nbsp;</h3>
      <%= select_tag 'student', options_for_select(@possible_students.map{ |u| [u.rut] }), {:multiple => true, :size => 5}   %>
      <%= hidden_field_tag 'course', @course.id %>
    </div>
    <%= submit_tag("Add", class:'btn-primary') %>
<% end %>
<br>

<h3>Current Students</h3>

<table class="basic_table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Last Name</th>
    <th>RUT</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @current_students.each do |students| %>
      <tr>
      <td><%= students.name %></td>
        <td><%= students.last_name %></td>
        <td><%= students.rut %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/add_teacher.html.erb
<h1>Course</h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Teacher</th>
    <th>Subject</th>
    <th>Grade</th>
    <th>Level</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
      <tr>
        <td><%= course.teacher.name %></td>
        <td><%= course.subject %></td>
        <td><%= course.grade %></td>
        <td><%= course.level %></td>
        <td><%= link_to 'Edit teacher', edit_course_path(course), class:'blue_btn' %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Course', new_course_path, class:'blue_btn' %>

app/views/admin/display.html.erb
<div class="card center">
  <div class="card-header" data-background-color="blue">
    <h2 class="title">Admin Panel</h2>
    <h3 class="title">options</h3>
  </div>
  <div class="card-content ">
    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'Add Teachers to Course', admin_add_teacher_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>

    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'Add Student to Course', admin_add_student_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>

    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'View All enrolled students', admin_student_courses_index_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>
    <!--
    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'View assistance', assistances_path%></a></h4>
          <br>

        </div>
      </div>
    </section>
    -->
    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'View All Courses and assistance', courses_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>

    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'Teachers', teachers_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>

    <section>
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 text">
          <h4 class="uppercase mb16"><a><%= link_to 'Students', students_path, class: "btn btn-deep-blue big-white"%></a></h4>
          <br>

        </div>
      </div>
    </section>
  </div>
</div>

app/views/admin/student_courses_index.html.erb
<h1>Students Enroled </h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Subject1</th>
    <th>Grade</th>
    <th>Level</th>
    <th>Student RUT </th>
    <th>Assistance</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
        <% course.students.each do |students| %>
          <tr>
            <td><%= course.subject %></td>
            <td><%= course.grade %></td>
            <td><%= course.level %></td>
            <td><%= students.rut %></td>
            <td ><%= link_to 'See Assistance', students, class:'blue_btn' %></td>
          </tr>
  <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class:'blue_btn' %>