config/routes.rb
# Rails router
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/home'

  resources :students do
    collection do
      get 'own_index'
    end
  end
  devise_for :teachers

  resources :courses do
    collection do
      get 'own_index'
    end
    member do
      get :all_qr
      post :export
    end
    resources :students
    resources :assistances, only: [:index]
  end

  resources :teachers do
    collection {post :import}
  end

  resources :students do
    collection { post :import }
    member do
      get :generate_qr
    end
  end

  resources :teachers do
    resources :courses do
      resources :students
    end
  end

  resources :assistances, only: [:index] do
    member do
      put :change_assist
    end
  end

  get 'welcome/index'

  get 'admin/display'
  get 'admin/add_teacher'
  get 'admin/add_student'
  get 'admin/add_student2'
  post 'admin/add_student3'
  get 'admin/student_courses_index'

  get 'welcome/metrics', to: 'welcome#metrics', as: 'welcome_metrics'
  get 'welcome/data', to: 'welcome#data', as: 'welcome_data'
  get 'welcome/student', to: 'welcome#student', as: 'welcome_student'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'Teacher', at: 'auth'
      get 'course_students' => 'content#course_students'
      post 'record_assistance' => 'content#record_assistance'
      delete 'assistance' => 'content#destroy_assistance'
      delete 'all_assistance' => 'content#destroy_all_assistance'
      scope 'course_assistance' do
        get '/:id/:date' => 'content#daily_course_assistance'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :all_qr, :export]
  before_action :authenticate_teacher!
  before_action :authenticate_admin!, except: [:own_index, :show]


  def export
    @assistance = []
    @assistance = []
    aux = Assistance.all
    aux.each do |ass|
      @assistance << ass if ass.course_id == @course.id
    end
    @dates = []
    @assistance.each do |ass|
      @dates << ass.date unless @dates.include?(ass.date)
    end
    send_data @course.export(@dates),
              filename: "#{@course.grade}-#{@course.subject}-#{@course.level}-grades.csv"
  end

  def all_qr
    tmp_path = @course.zip_all_qr
    send_file tmp_path, type: 'application/zip',
              disposition: 'attachment',
              filename: "#{@course.grade}-#{@course.subject}-#{@course.level}.zip"
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  def own_index
    @courses = Course.where(teacher: current_teacher)
    render 'index'
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @assistance = []
    @assistance = []
    aux = Assistance.all
    aux.each do |ass|
      @assistance << ass if ass.course_id == @course.id
    end
    @dates = []
    @assistance.each do |ass|
      @dates << ass.date unless @dates.include?(ass.date)
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
    @teachers = Teacher.all
  end

  # GET /courses/1/edit
  def edit
    @teachers = Teacher.all
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        @course.teacher = Teacher.where(email: params[:teacher]).first
        @course.save
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # TODO teacher_id is strange, hot fix tmb en course form
  def course_params
    params.require(:course).permit(:teacher, :subject, :grade, :level, :teacher_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def last_attendence
    course_aux = nil
    last_assist = Date.new(2010, 1, 1)
    current_teacher.courses.each do |course|
      course.assistances.each do |assist|
        course_aux = course if assist.date > last_assist
      end
    end
    course_aux
  end

  def find_assist(date, student_id, course_id)
    aux = Assistance.where(student_id: student_id, course_id: course_id)
    aux = aux.where('date BETWEEN ? AND ?', date.beginning_of_day,
                    date.end_of_day).first
    unless aux
      aux = Assistance.create(date: date, student_id: student_id,
                              course_id: course_id, attend: false)
    end
    puts date
    aux.id
  end
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :teacher %><br>
    <%= form.select :teacher_id, options_for_select(@teachers.all.map{ |u| [u.email, u.id] })   %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :course_subject, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade, id: :course_grade, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :course_level, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn-primary' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="card center">
  <div class="card-header" data-background-color="blue">
    <h2 class="title">Editing Course Info OR Change Teacher</h2>
  </div>
  <div class="card-content ">
    <%= render 'form', course: @course %>
  </div>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>
  <table class="basic_table">
    <thead>
    <tr>
      <th>Teacher</th>
      <th>Subject</th>
      <th>Grade</th>
      <th>Level</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
        <tr>
          <td><%= course.teacher.name %></td>
          <td><%= course.subject %></td>
          <td><%= course.grade %></td>
          <td><%= course.level %></td>
          <th><%= link_to 'GO to details', course, class:"blue_btn" %></th>
          <th ><%= link_to 'Generate ALL QR', all_qr_course_path(course.id), class:'blue_btn' %><td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Course', new_course_path, class:"blue_btn" %>

app/views/courses/new.html.erb
<div class="card center">
  <div class="card-header" data-background-color="blue">
    <h2 class="title">New Course</h2>
  </div>
  <div class="card-content ">
    <%= render 'form', course: @course %>
    <%= link_to 'Back', courses_path %>
  </div>
</div>

app/views/courses/show.html.erb
<p>
<h1>Course:
  <% if @course.subject!=nil %>
      <% if @course.grade!=nil %>
          <% if @course.level!=nil %>
              <%= @course.subject + ' '+ @course.grade + '-' + @course.level%>
          <% else %>
              <%= @course.subject + ' '+ @course.grade%>
          <% end %>
      <% else %>
          <% if @course.level!=nil %>
              <%= @course.subject + ' ' +@course.level%>
          <% else %>
              <%= @course.subject%>
          <% end %>
      <% end %>
  <% else %>
      <% if @course.grade!=nil %>
          <% if @course.level!=nil %>
              <%= @course.grade + '-' + @course.level%>
          <% else %>
              <%= @course.grade%>
          <% end %>
      <% else %>
          <% if @course.level!=nil %>
              <%= @course.level%>
          <% end %>
      <% end %>
  <% end %>
</h1>

</p>
<p>
  <strong>Teacher:</strong>
  <%= @course.teacher.name%>
</p>

<h1>Assistances</h1>

<table class="basic_table">
  <thead>
  <tr>
    <th>Student</th>
    <th>rut</th>
    <% @dates.sort_by {|date| date}.each do |date| %>
        <td><%= date.strftime('%d-%m-%y') %></td>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @course.students.each do |student| %>
      <tr>
        <td>
          <% if student.last_name != nil%>
              <%= student.name + ' '+student.last_name %>
          <% else %>
              <%= student.name %>
          <% end %>
        </td>
        <td><%= student.rut %></td>
        <% @dates.sort_by {|date| date}.each do |date| %>
            <% aux = false %>
            <% student.assistances.where(course_id: @course.id).sort_by{|e| e[:date]}.each do |assistance| %>
                <% if assistance.date.strftime('%d-%m-%y') == date.strftime('%d-%m-%y') %>
                    <% if assistance.attend %>
                        <% aux = true %>
                    <%end%>
                <% end %>
            <% end %>
            <% if aux %>
                <td bgcolor="#88ff88">
                  yes
                </td>
            <%else%>
                <td bgcolor="#ff8888"
                >
                  no
                </td>
            <%end%>
        <%end%>
      </tr>
  <% end %>
  </tbody>
</table>
<div>
  <h1>Export</h1>
  <%= button_to "Export Attendece to CSV", export_course_path, class:'btn-success'%>
</div>
</br>