config/routes.rb
# Rails router
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/home'

  resources :students do
    collection do
      get 'own_index'
    end
  end
  devise_for :teachers

  resources :courses do
    collection do
      get 'own_index'
    end
    member do
      get :all_qr
      post :export
    end
    resources :students
    resources :assistances, only: [:index]
  end

  resources :teachers do
    collection {post :import}
  end

  resources :students do
    collection { post :import }
    member do
      get :generate_qr
    end
  end

  resources :teachers do
    resources :courses do
      resources :students
    end
  end

  resources :assistances, only: [:index] do
    member do
      put :change_assist
    end
  end

  get 'welcome/index'

  get 'admin/display'
  get 'admin/add_teacher'
  get 'admin/add_student'
  get 'admin/add_student2'
  post 'admin/add_student3'
  get 'admin/student_courses_index'

  get 'welcome/metrics', to: 'welcome#metrics', as: 'welcome_metrics'
  get 'welcome/data', to: 'welcome#data', as: 'welcome_data'
  get 'welcome/student', to: 'welcome#student', as: 'welcome_student'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'Teacher', at: 'auth'
      get 'course_students' => 'content#course_students'
      post 'record_assistance' => 'content#record_assistance'
      delete 'assistance' => 'content#destroy_assistance'
      delete 'all_assistance' => 'content#destroy_all_assistance'
      scope 'course_assistance' do
        get '/:id/:date' => 'content#daily_course_assistance'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesarrolloDeSoftwareAssistapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div id="wrapper">

          <!-- Navigation -->
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                <%= link_to 'AssistApp', root_path, class: "navbar-brand", method: :get %>

              </div>
              <!-- Top Menu Items -->
              <ul class="nav navbar-right top-nav">
                <% if teacher_signed_in? %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                          <%=current_teacher.name %>
                        <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                          <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                          <%= link_to('Logout', destroy_teacher_session_path, class: "fa fa-fw fa-power-off", :method => :delete) %>
                        </li>
                      </ul>
                    </li>
                    </ul>
                <%else%>
                  <a><%= link_to 'Log In', new_teacher_session_path, method: :get, :class =>"navbar-brand" %> </a>
                <%end%>
              <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                <% if teacher_signed_in? %>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                      <ul class="nav navbar-nav side-nav">
                        <li class="active">
                          <%= link_to 'Home', root_path, class:'fa fa-fw fa-dashboard', method: :get %>
                        </li>
                        <li>
                          <%= link_to 'Courses', own_index_courses_path, class:'fa fa-fw fa-dashboard', method: :get %>
                        </li>
                        <li>
                          <%= link_to 'Students', own_index_students_path, class:'fa fa-fw fa-dashboard', method: :get %>
                        </li>
                        <li>
                          <%= link_to 'Metrics', welcome_metrics_url, class:'fa fa-fw fa-dashboard', method: :get %>
                        </li>
                        <li>
                          <% if current_teacher.admin == true %>
                              <%= link_to 'Admin', admin_display_path, class: 'fa fa-fw fa-desktop', method: :get %>
                          <% end%>
                        </li>
                      </ul>
                    </div>
                <% end%>

                <!-- /.navbar-collapse -->
          </nav>
            <div id="page-wrapper">
              <%= yield %>
            </div>
            <!-- /#page-wrapper -->

        </div>

  </body>
</html>